name: campus_crush
description: A social networking app for campus community.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  shared_preferences: ^2.0.17
  flutter_secure_storage: ^8.0.0
  json_annotation: ^4.9.0
  intl: ^0.17.0
  timeago: ^3.3.0
  image_picker: ^0.8.6+4
  path: ^1.8.2
  path_provider: ^2.0.13
  flutter_svg: ^2.0.5
  cached_network_image: ^3.2.3
  url_launcher: ^6.1.10
  internet_connection_checker: ^1.0.0+1
  dio: ^5.0.0
  font_awesome_flutter: ^10.4.0
  get_it: ^7.6.0
  uuid: ^3.0.7
  flutter_cache_manager: ^3.3.0
  image_cropper: ^4.0.1
  google_sign_in: ^6.1.5
  firebase_core: ^2.17.0
  firebase_auth: ^4.2.2
  synchronized: ^3.0.0
  http_parser: ^4.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  build_runner: ^2.3.3
  json_serializable: ^6.6.1
  flutter_launcher_icons: ^0.13.1
  mockito: ^5.4.2
  flutter_driver:
    sdk: flutter
  integration_test:
    sdk: flutter
  test: ^1.24.0
  bloc_test: ^9.1.5
  mocktail: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
  # Removed the missing assets/icons/ directory
  # fonts:
  #   - family: Poppins
  #     fonts:
  #       - asset: assets/fonts/Poppins-Regular.ttf
  #       - asset: assets/fonts/Poppins-Medium.ttf
  #         weight: 500
  #       - asset: assets/fonts/Poppins-SemiBold.ttf
  #         weight: 600
  #       - asset: assets/fonts/Poppins-Bold.ttf
  #         weight: 700 